name: Python application test deploy

on:
 push:
    branches: [ main ]
   
jobs:
 create:
   runs-on: ubuntu-18.04
   steps:
     - name: Check Out Repo
       uses: actions/checkout@v2
       
     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_HUB_LOGIN }}
         password: ${{ secrets.DOCKER_HUB_PWD }}

     - name: Set up Docker Buildx
       id: buildx
       uses: docker/setup-buildx-action@v1
       
     - name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         context: ./
         file: ./Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_HUB_LOGIN }}/tst:test_image
         
     - name: deploy
       id: delp
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USERNAME }}
        password: ${{ secrets.MAIN_PWD }}
        port: ${{ secrets.MAIN_PORT }}
        script: |
          docker stop test_flask || true && docker rm test_flask || true
          docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} -p ${{ secrets.DOCKER_HUB_PWD }}
          docker pull ${{ secrets.DOCKER_HUB_LOGIN }}/tst:test_image
          docker run --name test_flask -d -p 5000:5000 ${{ secrets.DOCKER_HUB_LOGIN }}/tst:test_image
    


         
